name: Create Release and Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build_linux_wheel:
    name: Build wheel on AlmaLinux 8
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - name: Install Development Tools, git and python
        run: |
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          dnf groupinstall -y "Development Tools"
          # Install GCC 12
          dnf install -y gcc-toolset-12 git python312 python3.12-devel curl ninja-build
          ln -s /usr/bin/python3.12 /usr/bin/python
      - name: Install pip
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          rm get-pip.py
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/build.txt
          pip install wheel psutil
      - name: Build wheel
        run: |
          source /opt/rh/gcc-toolset-12/enable
          CC=gcc CXX=g++ CUDAHOSTCXX=g++ pip wheel . --no-build-isolation --wheel-dir=./dist -v
      - name: Store wheel
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel-linux
          path: dist/mmcv*.whl

  build_windows_wheel:
    name: Build wheel on Windows
    runs-on: windows-2022
    env:
      MAX_JOBS: 4
      DISTUTILS_USE_SDK: 1
      CUDA_PATH: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1"
      CUDA_PATH_V12_1: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install CUDA 12.1
        run: |
          echo "Downloading CUDA 12.1..."
          curl.exe -fSLo cuda_installer.exe https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_531.14_windows.exe
          echo "Installing CUDA 12.1..."
          Start-Process -FilePath .\cuda_installer.exe -ArgumentList "-s", "-n", "-f" -Wait
          del cuda_installer.exe
          echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin" >> $env:GITHUB_PATH
          echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp" >> $env:GITHUB_PATH
        shell: powershell
      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/build.txt
          pip install wheel psutil
      - name: Build wheel
        run: |
          where cl.exe
          pip wheel . --no-build-isolation --wheel-dir=./dist -v
        shell: cmd
      - name: Store wheel
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel-windows
          path: dist/mmcv*.whl

  create_release:
    name: Create GitHub Release
    permissions:
      contents: write
    needs: [build_linux_wheel, build_windows_wheel]
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create Release and Upload Wheels
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/python-wheel-linux/mmcv*.whl
            dist/python-wheel-windows/mmcv*.whl
